version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Check Versions"
          command: |
            node -v 
            npm -v
      - run:
          name: "Install Zowe CLI"
          command: |
            sudo npm i -g @zowe/cli@6.7.0 --@zowe:registry=https://registry.npmjs.org --no-package-lock --force --ignore-scripts
      - run:
          name: "Install Packages"
          command: |
            npm i .
      - run:
          name: "Compile Scripts"
          command: |
            npm run compile:scripts
      - run:
          name: "Create Zowe Profiles"
          command: |
            zowe -V
            zowe profiles create zosmf zxplore --host $host --port $port --user $user --pass $pass --ru false
      - run:
          name: "Build and Test"
          command: |
            npm run build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build